language: php

php:
  - 7.0
  - 7.1

before_script:
  - cp .env.testing .env
  - mysql -e 'create database cupa_test;'
  - composer install --no-interaction
  - php artisan key:generate

script:
  - sh testme.sh
