<?php

return [
    'importDb' => [
        'host' => 'hostname',
        'name' => 'dbname',
        'user' => 'username',
        'pass' => 'password',
    ],
    'queryCache' => 5,
    'ages' => [
        'min' => 13,
        'max' => 70,
    ],
    'facebook' => [
        'appId' => '',
        'secret' => '',
        'fileUpload' => false,
        'allowSignedRequest' => false,
    ],
    'paypal' => [
        'api_username' => env('PAYPAL_USERNAME'),
        'api_password' => env('PAYPAL_PASSWORD'),
        'api_signature' => env('PAYPAL_SIGNATURE'),
    ],
    'volunteer' => [
        'involvement' => [
            '0-1 year' => '0-1 year',
            '2-4 years' => '2-4 years',
            '5-9 years' => '5-9 years',
            '10+ years' => '10+ years',
        ],
        'primary_interest' => [
            'Youth Outreach Events' => 'Youth Outreach Events',
            'Running CUPA Leagues' => 'Running CUPA Leagues',
            'Running CUPA Sponsored Tournaments' => 'Running CUPA Sponsored Tournaments',
            'Helping with USA Ultimate Sponsored Tournaments' => 'Helping with USA Ultimate Sponsored Tournaments',
            'Helping with General Volunteer Tasks' => 'Helping with General Volunteer Tasks',
            'Large Event Help - Various Tasks' => 'Large Event Help - Various Tasks',
            'Off-Field Event Help' => 'Off-Field Event Help',
            'Public Relations Efforts' => 'Public Relations Efforts',
            'Other' => 'Other',
        ],
    ],
    'clinics' => [
        'youth',
        'adult',
    ],
    'distinctSeasons' => [
        0 => 'Select Season',
        'winter' => 'Winter',
        'spring' => 'Spring',
        'summer' => 'Summer',
        'fall' => 'Fall',
    ],
    'seasons' => [
        1 => 'winter',
        2 => 'winter',
        3 => 'spring',
        4 => 'spring',
        5 => 'summer',
        6 => 'summer',
        7 => 'summer',
        8 => 'fall',
        9 => 'fall',
        10 => 'fall',
        11 => 'fall',
        12 => 'winter',
    ],
    'levels' => [
        'New',
        'Pickup',
        'Leagues',
        'College',
        'Club',
        'College Regionals',
        'Club Regionals',
        'AUDL/MLU',
        'College Nationals',
        'Club Nationals',
        'Worlds',
    ],
    'divisions' => [
        'open',
        'womens',
        'mixed',
        'youth_open',
        'youth_womens',
        'youth_mixed',
        'masters',
        'grand_masters',
    ],
    'teamTypes' => [
        'Open',
        'Women\'s',
        'Mixed',
        'Masters',
        'Women\'s Masters',
        'Grand Masters',
    ],
    'league_menu' => [
        'league_teams' => [
            'name' => 'Teams',
            'auth' => null,
        ],
        'league_schedule' => [
            'name' => 'Schedule',
            'auth' => null,
        ],
        'league_email' => [
            'name' => 'Contacts',
            'auth' => null,
        ],
        'league_coaches' => [
            'name' => 'Coaches',
            'auth' => 'coach',
        ],
    ],
    'league_manage_menu' => [
        'league_shirts' => [
            'name' => 'Shirts',
            'auth' => 'edit',
        ],
        'league_emergency' => [
            'name' => 'Emergency',
            'auth' => 'edit',
        ],
        'league_requests' => [
            'name' => 'Requests',
            'auth' => 'edit',
        ],
        'league_players' => [
            'name' => 'Players',
            'auth' => 'edit',
        ],
        'league_waitlist' => [
            'name' => 'Waitlist',
            'auth' => 'edit',
        ],
        'league_status' => [
            'name' => 'Status',
            'auth' => 'edit',
        ],
        'league_manage' => [
            'name' => 'Manage',
            'auth' => 'edit',
        ],
    ],
    'shirts' => [
        'YS' => 'Youth Small',
        'YM' => 'Youth Medium',
        'YL' => 'Youth Large',
        'XS' => 'X Small',
        'S' => 'Small',
        'M' => 'Medium',
        'L' => 'Large',
        'XL' => 'X Large',
        'XXL' => 'XX Large',
    ],
    'days' => [
        '0' => 'Select Day',
        'Sunday' => 'Sunday',
        'Monday' => 'Monday',
        'Tuesday' => 'Tuesday',
        'Wednesday' => 'Wednesday',
        'Thursday' => 'Thursday',
        'Friday' => 'Friday',
        'Saturday' => 'Saturday',
    ],
    'leagueTypes' => [
        'league' => 'League',
        'hat' => 'Hat Tournament',
    ],
    'leagueDefaultQuestions' => ['24-1', '4-0', '5-1', '2-1', '3-1', '6-1', '33-1', '32-1', '31-1', '8-0'],
    'coachingRequirements' => [
        'background' => 'Background Check',
        'concussion' => 'Concussion Training',
        //'chaperon' => 'Chaperon Form',
        'manual' => 'Read Manual',
        'rules' => 'Read Rules',
        //'usau' => 'USAU Requirements',
    ],
    'postCategories' => [
        '0' => 'Select Category',
        'league' => 'Leagues',
        'youth' => 'Youth',
        'around' => 'Pickup/Tournaments',
        'other' => 'Other',
    ],
    'profileMenu' => [
        'profile_public' => 'Public Profile',
        'profile' => 'Personal',
        'profile_leagues' => 'My Leagues',
        'profile_minors' => 'My Minors',
        'profile_contacts' => 'My Contacts',
        'profile_password' => 'Password Change',
    ],
];
